import { Toaster } from "@/components/ui/toaster";
import ReactQueryProvider from "@/lib/react-query";
import "./globals.css";
import { MDXProvider } from "@mdx-js/react";
// import "./mdx-styles.css";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>{children}</ReactQueryProvider>
        <Toaster />
      </body>
    </html>
  );
}
